### ISSUE TITLE
No partial matching?

### ISSUE THREAD

**Issue by oleander** [jhurliman/node-echoprint-server#13]
I took a look at the implementation and only saw full fingerprint matching against the database, no partial matching. That that would mean that the echoprint client have to generate an exact replica of the fingerprints already existing in the database, or I'm I wrong?

``` js
  var sql = 'SELECT track_id,COUNT(track_id) AS score ' +
    'FROM codes ' +
    'WHERE code IN (' + fpCodesStr + ') ' +
    'GROUP BY track_id ' +
    'ORDER BY score DESC ' +
    'LIMIT ' + rows;
```

**Comment by jhurliman** [comment]
Echoprint's audio fingerprints are composed of lots of small hashes ("codes") representing only a few hundred milliseconds of audio. That SQL query you pasted is counting the number of matching codes grouped by track, where the track with the most code matches would be considered the closest match.

**Comment by oleander** [comment]
Aha, I get it. Thanks for your respons.
