### ISSUE TITLE
Porting database from Echoprint Server Echonest

### ISSUE THREAD

**Issue by EnricoGiordano1992** [jhurliman/node-echoprint-server#22]
Hi, I'm evaluating your echoprint implementation (you have done a great work!). I have a classic echoprint database of some songs, the model is of echoprint server echonest. Now I want to test my database in your node server; is there a way to import my database (solr) in MySQL database? How can I map the exported CSV into a SQL file compatible with your data model?

Thanks!

**Comment by jhurliman** [comment]
Hi, I apologize but I don't have the capacity to actively maintain this server anymore now that I do not work with audio fingerprinting on a regular basis. I believe what you want to do is achievable (assuming your echoprints were generated with a compatible echoprint client) but it would require some custom code to convert between CSV and SQL formats.
