### ISSUE TITLE
Problem Accuracy echoprint-server

### ISSUE THREAD

**Issue by devops85** [jhurliman/node-echoprint-server#3]
Hi Team,

Well, I've installed your Node.js echoprint-server in Windows but I am facing a problem with the accuracy recogniction.

For example i've downladed the following sound:
http://www.youtube.com/watch?v=_-0MXklxHlQ in 11025Hz, Mono, 16 bits. I've generated a echoprint codegen (40 secs) and then I uploaded it succesfully to my echoprint server. 

After that, I download a new sound (another video but with the same sound): 
http://www.youtube.com/watch?v=XtS22a-UrA8 also in 11025Hz, Mono, 16 bits. Then I've generated a echoprint codegen (40 secs) and then I sent a GET request to my server, but it doesnt match :(

Then, I made a last test. I've generated an ENMFP codegen with the second sound (about 70 secs) and I sent the fp_code to Echonest API Server and they detected the artist and the track name.

So How can I improve the accuracy?, I want to implement this server and recognize sounds. 

Could you please shed some light here?.

Thanks in advance

**Comment by jhurliman** [comment]
I downloaded both of those tracks and ran them through echoprint-codegen, ingested the fingerprint for _-0MXklxHlQ and was able to match both _-0MXklxHlQ and XtS22a-UrA8 against the ingested fingerprint. You will probably need to send me the exact audio files you used plus the parameters you passed to echoprint-codegen if you are only taking 40 second samples of the full tracks. Is it possible that you are using the first 40 seconds of the second track and the actual song starts later on in the video?

**Comment by devops85** [comment]
Hi  jhurliman,
Thank you for your reply. Yes, I am sending the first 40 secs of the video, because I am trying to develop a system such can identify background music from Videos in an automatic way. 
I am very interesting in use your echonest server, It looks so good. Do you know How can I improve the accuracy of the sound recognition in order to indentify background music from videos?.

Thanks in advance.

**Comment by jhurliman** [comment]
Can you send me the exact parameters you gave to echoprint-codegen so I can reproduce the issue? There is no simple fix aside from recreating the issue and trying to understand why the match failed. As a rule of thumb though, try to avoid the intro/outro of songs and use a clip from the middle instead. Also, make sure you are creating the initial ingested fingerprint from the entire track and not just a snippet.

**Comment by jhurliman** [comment]
There hasn't been any activity on this issue for a while so I'm going to close it. Please feel free to reopen or create a new ticket if you're still having issues.

**Comment by SolSeyoum** [comment]
Hi Jhurliman,
 How to ingest a json file to generated by codegen for multiple music files. For a single file, I paste the json file on http://localhost:37760/debug and click the ingest button works fine. But for json file with multiple musics, it only shows sucess for the first music in the json, not for all the musics.

I would appreciate if you advice me on this. Thanks in advance.
Solomon
