### ISSUE TITLE
cannot add track on mac

### ISSUE THREAD

**Issue by lovechaninbetter** [jhurliman/node-echoprint-server#4]
after i posted/ingest myterminal said:

/Applications/XAMPP/xamppfiles/htdocs/node-echoprint-server/controllers/fingerprinter.js:40
  zlib.inflate(compressed, function(err, uncompressed) {
       ^
TypeError: Object #<Object> has no method 'inflate'
    at Object.decodeCodeString (/Applications/XAMPP/xamppfiles/htdocs/node-echoprint-server/controllers/fingerprinter.js:40:8)
    at Object.ingest (/Applications/XAMPP/xamppfiles/htdocs/node-echoprint-server/controllers/api.js:60:17)
    at IncomingMessage.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/node-echoprint-server/server.js:43:22)
    at IncomingMessage.emit (events.js:64:17)
    at HTTPParser.onMessageComplete (http.js:137:23)
    at Socket.ondata (http.js:1375:22)
    at TCP.onread (net.js:334:27)

what is the error said.? or can i manually insert it?

thanks .

**Comment by jhurliman** [comment]
Can you tell me what version of node.js you are running? You can find out by running `node -v` on the command line

**Comment by lovechaninbetter** [comment]
i found out that the error above (TypeError: Object # has no method 'inflate')  is because my node version is 0.5.

i  then upgraded node to lastest version ( 0.8.12)  and posted/ingest while running index.js 

terminal said:

debug: Inflated 3124 byte code string into 894 codes
info: Ingesting track "payphone" by artist "maroon 5", 348 seconds, 894 codes
error: Failed to ingest track: Missing required track fields

i am sure that i edited config.local.js to suit my environment correctly.

thanks for ur support. jhurliman.

**Comment by jhurliman** [comment]
Looks like the code is working properly now. Make sure that you are sending all of the required fields to get it to actually ingest a track fingerprint though.

**Comment by lovechaninbetter** [comment]
hi  jhurliman. me again :)

look like my server (localhost) did not get "track" data . i am sure that track data was included in post data.

see my form upload >> https://dl.dropbox.com/u/12797378/index.php

my terminal still said

info: Ingesting track "Kalimba" by artist "Mr. Scruff", 348 seconds, 894 codes
error: Failed to ingest track: Missing required track fields

thanks.

**Comment by jhurliman** [comment]
Try passing in another field called "length" with the value "0" and let me know if that works.

**Comment by lovechaninbetter** [comment]
thanks  jhurliman. i did it successfully so i can do ingestion. I dont know where i did mistake. sorry.

next issue, i try a track matching with the same song in database many times >  no song matched.  any suggestions?  

my echo version is 4.12.

sorry for my poor english.

**Comment by jhurliman** [comment]
A lot of fixes were made recently. I'm going to close this ticket since there hasn't been any activity, but please feel free to reopen it or create a new ticket if you're still having issues with the latest version.
