### ISSUE TITLE
Import data from the original Echoprint system?

### ISSUE THREAD

**Issue by bgood-clip** [jhurliman/node-echoprint-server#5]
I'm in the process of migrating to this implementation of the Echoprint server, from the original implementation (released under the Echonest organization).  Is it possible to import the codes from the original Echoprint system?

Thanks in advance
Ben

**Comment by jhurliman** [comment]
I haven't looked into this specifically, but the first question would be if you can extract codes from the original Echoprint system as JSON dumps? Using the same format that the command-line fingerprinting tool outputs. If so, it should be straightforward.

**Comment by jhurliman** [comment]
There hasn't been any activity on this issue in a while so I'm going to close it. Please feel free to reopen the ticket or create a new one if you're still looking into this.
