### ISSUE TITLE
How to run this application...

### ISSUE THREAD

**Issue by shinurag** [jhurliman/node-echoprint-server#7]
Hi,
Im new with this node.js server, so i dont know how to run this.. please guide me..

the things i did yet..

In command prompt:
C:\node-echoprint-server>node index.js
info: Loaded settings from config.local.js. Database is echoprint@localhost

but after this in crome browser (http://localhost:37760/), i can see  {"error":"Invalid API endpoint"} .... actually i havn't any idea how to run this.. my goal is to develop an android app with SQLite database instead of MySql.

Please help me..

Thanks
Shinurag

**Comment by shinurag** [comment]
I found the solution..

**Comment by jhurliman** [comment]
Can you leave some information on what you did, in case someone else runs into a similar issue?

**Comment by shinurag** [comment]
okay.
used the database mysql by installing wamp server(for linux its lamp), after listening node server, open the url 
1. for debugging: http://localhost:37760/debug
2. for get the matching result: http://localhost:37760/query?code=< codegen generated code >&version=4.12

**Comment by jhurliman** [comment]
Glad you got it working, thanks!
